const data = {
  products: [
    {
      _id: '1',
      name: 'Short and Shirt',
      category: 'Boy',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'T-Shirt + Pant',
      category: 'Girl',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: '(Cotton & Orange) Short and T-Shirt',
      category: 'Mixte',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Dress',
      category: 'Girl',
      image: '/images/p4.jpg',
      price: 250,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '5',
      name: 'Wonderchild Romper',
      category: 'Mixte',
      image: '/images/p5.jpg',
      price: 450,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '6',
      name: 'Princess Dress',
      category: 'Girl',
      image: '/images/p6.jpg',
      price: 300,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '7',
      name: 'Short and Shirt',
      category: 'Boy',
      image: '/images/p7.jpg',
      price: 300,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '8',
      name: 'T-Shirt',
      category: 'Boy',
      image: '/images/p8.jpg',
      price: 400,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '9',
      name: 'Sleeves T-Shirt',
      category: 'Girl',
      image: '/images/p9.jpg',
      price: 500,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '10',
      name: 'Dress',
      category: 'Girl',
      image: '/images/p10.jpg',
      price: 150,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '11',
      name: 'Rolando Jaimito',
      category: 'Boy',
      image: '/images/p11.jpg',
      price: 450,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '12',
      name: 'Princess Dress',
      category: 'Girl',
      image: '/images/p12.jpg',
      price: 200,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '13',
      name: 'Wonderchild Romper',
      category: 'Mixte',
      image: '/images/p13.jpg',
      price: 350,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '14',
      name: ' Full Striped Pants',
      category: 'Boy',
      image: '/images/p14.jpg',
      price: 450,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '15',
      name: "Infant's Cartoon  Koala",
      category: 'Girl',
      image: '/images/p15.jpg',
      price: 300,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
