const data = {
  products: [
    {
      _id: '1',
      name: 'Short and Shirt',
      category: 'Boy',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '2',
      name: 'T-Shirt + Pant',
      category: 'Girl',
      image: '/images/p2.jpg',
      price: 150,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: '(Cotton & Orange) Short and T-Shirt',
      category: 'Mixte',
      image: '/images/p3.jpg',
      price: 100,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Dress',
      category: 'Girl',
      image: '/images/p4.jpg',
      price: 250,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      _id: '5',
      name: 'Wonderchild Romper',
      category: 'Mixte',
      image: '/images/p5.jpg',
      price: 450,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      _id: '6',
      name: 'Princess Dress',
      category: 'Girl',
      image: '/images/p6.jpg',
      price: 300,
      countInStock: 20,
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};

export default data;
